name: Deploy to Homelab

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    uses: whodrey-labs/homelab-actions/.github/workflows/deploy-homelab.yml@main
    with:
      deploy_path: ${{ vars.HOMELAB_DEPLOY_PATH }}
      compose_file: compose.prod.yml
      branch: main
      use_tailscale: true
    secrets: inherit
